//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.08 at 10:25:17 PM CST 
//


package org.openhab.core.model.persist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="thresholdFilter" type="{}ThresholdFilter"/>
 *         &lt;element name="timeFilter" type="{}TimeFilter"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterList", propOrder = {
    "thresholdFiltersAndTimeFilters"
})
public class FilterList {

    @XmlElements({
        @XmlElement(name = "thresholdFilter", type = ThresholdFilter.class),
        @XmlElement(name = "timeFilter", type = TimeFilter.class)
    })
    protected List<Filter> thresholdFiltersAndTimeFilters;

    /**
     * Gets the value of the thresholdFiltersAndTimeFilters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thresholdFiltersAndTimeFilters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThresholdFiltersAndTimeFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ThresholdFilter }
     * {@link TimeFilter }
     * 
     * 
     */
    public List<Filter> getThresholdFiltersAndTimeFilters() {
        if (thresholdFiltersAndTimeFilters == null) {
            thresholdFiltersAndTimeFilters = new ArrayList<Filter>();
        }
        return this.thresholdFiltersAndTimeFilters;
    }

}
