//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.08 at 10:25:17 PM CST 
//


package org.openhab.core.model.persist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openhab.core.model.Model;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{CoreModel}Model">
 *       &lt;sequence>
 *         &lt;element name="strategies" type="{}StrategyList"/>
 *         &lt;element name="filters" type="{}FilterList" minOccurs="0"/>
 *         &lt;element name="configs" type="{}ConfigList"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "strategies",
    "filters",
    "configs"
})
@XmlRootElement(name = "PersistenceModel")
public class PersistenceModel
    extends Model
{

    @XmlElement(required = true)
    protected StrategyList strategies;
    protected FilterList filters;
    @XmlElement(required = true)
    protected ConfigList configs;

    /**
     * Gets the value of the strategies property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyList }
     *     
     */
    public StrategyList getStrategies() {
        return strategies;
    }

    /**
     * Sets the value of the strategies property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyList }
     *     
     */
    public void setStrategies(StrategyList value) {
        this.strategies = value;
    }

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link FilterList }
     *     
     */
    public FilterList getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterList }
     *     
     */
    public void setFilters(FilterList value) {
        this.filters = value;
    }

    /**
     * Gets the value of the configs property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigList }
     *     
     */
    public ConfigList getConfigs() {
        return configs;
    }

    /**
     * Sets the value of the configs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigList }
     *     
     */
    public void setConfigs(ConfigList value) {
        this.configs = value;
    }

}
