//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 11:27:14 PM CST 
//


package org.openhab.core.model.items;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelGroupFunction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModelGroupFunction">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AND"/>
 *     &lt;enumeration value="OR"/>
 *     &lt;enumeration value="NAND"/>
 *     &lt;enumeration value="NOR"/>
 *     &lt;enumeration value="AVG"/>
 *     &lt;enumeration value="SUM"/>
 *     &lt;enumeration value="MAX"/>
 *     &lt;enumeration value="MIN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ModelGroupFunction")
@XmlEnum
public enum ModelGroupFunction {

    AND,
    OR,
    NAND,
    NOR,
    AVG,
    SUM,
    MAX,
    MIN;

    public String value() {
        return name();
    }

    public static ModelGroupFunction fromValue(String v) {
        return valueOf(v);
    }

}
