//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 11:27:14 PM CST 
//


package org.openhab.core.model.items;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openhab.core.model.items package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openhab.core.model.items
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModelGroupItem }
     * 
     */
    public ModelGroupItem createModelGroupItem() {
        return new ModelGroupItem();
    }

    /**
     * Create an instance of {@link ItemModel }
     * 
     */
    public ItemModel createItemModel() {
        return new ItemModel();
    }

    /**
     * Create an instance of {@link ModelNormalItem }
     * 
     */
    public ModelNormalItem createModelNormalItem() {
        return new ModelNormalItem();
    }

    /**
     * Create an instance of {@link ModelItem }
     * 
     */
    public ModelItem createModelItem() {
        return new ModelItem();
    }

    /**
     * Create an instance of {@link ModelBinding }
     * 
     */
    public ModelBinding createModelBinding() {
        return new ModelBinding();
    }

    /**
     * Create an instance of {@link ModelGroupItem.Function }
     * 
     */
    public ModelGroupItem.Function createModelGroupItemFunction() {
        return new ModelGroupItem.Function();
    }

}
