//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.12 at 11:13:58 PM CST 
//


package org.openhab.core.model.sitemap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkableWidget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkableWidget">
 *   &lt;complexContent>
 *     &lt;extension base="{}Widget">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="text" type="{}Text"/>
 *         &lt;element name="group" type="{}Group"/>
 *         &lt;element name="image" type="{}Image"/>
 *         &lt;element name="frame" type="{}Frame"/>
 *         &lt;element name="switch" type="{}Switch"/>
 *         &lt;element name="chart" type="{}Chart"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkableWidget", propOrder = {
    "children"
})
@XmlSeeAlso({
    Frame.class,
    Text.class,
    Image.class,
    Group.class
})
public class LinkableWidget
    extends Widget
{

    @XmlElements({
        @XmlElement(name = "text", type = Text.class),
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "image", type = Image.class),
        @XmlElement(name = "frame", type = Frame.class),
        @XmlElement(name = "switch", type = Switch.class),
        @XmlElement(name = "chart", type = Chart.class)
    })
    protected List<Widget> children;

    /**
     * Gets the value of the children property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the children property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Text }
     * {@link Group }
     * {@link Image }
     * {@link Frame }
     * {@link Switch }
     * {@link Chart }
     * 
     * 
     */
    public List<Widget> getChildren() {
        if (children == null) {
        	children = new ArrayList<Widget>();
        }
        return this.children;
    }

}
