//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.25 at 11:44:56 PM CST 
//


package org.openhab.core.model.sitemap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openhab.core.model.sitemap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openhab.core.model.sitemap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sitemap }
     * 
     */
    public Sitemap createSitemap() {
        return new Sitemap();
    }

    /**
     * Create an instance of {@link Frame }
     * 
     */
    public Frame createFrame() {
        return new Frame();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Switch }
     * 
     */
    public Switch createSwitch() {
        return new Switch();
    }

    /**
     * Create an instance of {@link Widget }
     * 
     */
    public Widget createWidget() {
        return new Widget();
    }

    /**
     * Create an instance of {@link Chart }
     * 
     */
    public Chart createChart() {
        return new Chart();
    }

    /**
     * Create an instance of {@link Setpoint }
     * 
     */
    public Setpoint createSetpoint() {
        return new Setpoint();
    }

    /**
     * Create an instance of {@link Slider }
     * 
     */
    public Slider createSlider() {
        return new Slider();
    }

    /**
     * Create an instance of {@link Colorpicker }
     * 
     */
    public Colorpicker createColorpicker() {
        return new Colorpicker();
    }

    /**
     * Create an instance of {@link Webview }
     * 
     */
    public Webview createWebview() {
        return new Webview();
    }

    /**
     * Create an instance of {@link LinkableWidget }
     * 
     */
    public LinkableWidget createLinkableWidget() {
        return new LinkableWidget();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link NonLinkableWidget }
     * 
     */
    public NonLinkableWidget createNonLinkableWidget() {
        return new NonLinkableWidget();
    }

    /**
     * Create an instance of {@link Selection }
     * 
     */
    public Selection createSelection() {
        return new Selection();
    }

}
